### ISSUE TITLE
Election Rules - Step 7

### ISSUE THREAD

**Issue by pjaclark** [TI-Tokyo/riak-community-admin#10]
## Run-off elections

Should we have run offs at all? What if the lowest ranked candidate is the best compromise candidate?

## What kind of majority vote to win?

Should we go for a majority vote (i.e. more votes than the other Candidates) over an overall majority vote (i.e. more than 50% of the votes) to win?

**Comment by pjaclark** [comment]
Decisions from 2017-09-08:

Minimum Quorum  - 10% of the eligible voters - to be revisited after more thought.
Minimum threshold to win - 20% of the actual voters.
No quorum or minimum threshold not met, PDG appoints someone and election is re-run.

Method of election: undecided.

Options presented are: 
- Borda (https://en.wikipedia.org/wiki/Borda_count)
- IRV (https://en.wikipedia.org/wiki/Instant-runoff_voting)

Other systems are listed here: https://en.wikipedia.org/wiki/Electoral_system

**Comment by Licenser** [comment]
I would add https://en.wikipedia.org/wiki/Schulze_method it seems widely used in other OSS projects like Debian, Ubuntu, Gentoo, FSF EU [and some others](https://en.wikipedia.org/wiki/Schulze_method#Users) so it probably is well codified (including example code in the article ;).

**Comment by pjaclark** [comment]
Decisions from 2017-09-15 - Going to use the Schulze Method for now.

**Comment by binarytemple** [comment]
This got very complicated - I can understand Instant Runoff Voting, find plenty of software implementations, and it's good enough for the following Nation states (from wikipedia page):

* Australia
* Canada
* Czech Republic
* Hong Kong
* India
* Ireland
* New Zealand
* Papua New Guinea
* United Kingdom
* United States

I cannot understand (without significant effort) - the Schulze method - although it's apparently  used by a load of open-source projects. 

Although my short attention span and general lack of intelligence are probably a contributing factor - I can't help but feel that the adoption of an easily understood method, with lots of implementations in multiple languages - might be beneficial to the general perception of project transparency.

**Comment by Licenser** [comment]
IRV is a very polarizing method as it leads to runoffs between direct competitors to find the 'strongest', single candidate. Schulze, on the other hand, tries to find the most accepted candidate which has the biggest consensus overall.

I honestly believe a consensus-based method will lead to a healthy community with fewer factions, silos or 'parties' and people will be free to vote (or rank) hey they feel rather than considering supporting a candidate that is 'more likely to win'.

## users 

As into who uses it, this applies to both the list of users of Schulze and IRV, without trying to understand as if why they use it, it really doesn't matter. If we'd subscribe to "Because big entity X use Y so we should too, it must be good enough then.", we'd all be using go and mongodb and would not be here to start with ;)

We are not a country. We don't transport ballots on horseback over thousands of kilometers, nor do we live in a time where electronic tallying of votes don't exist. We don't need to count by hand with watchdogs standing over them to prevent tampering. And most of all we have the choice and are not in the situation that we have an existing.

We live in a time where computation is cheap, our votes are not important enough to warrant the effort of tampering with the voting system, we don't need paper votes or observers.

From what I can tell that is why, huge, old, countries use IRV rather then Schulze and (in comparison) small organizations in the IT space seem to have adopted Schulz rather than IRV.

## complexity 

As to understandability, voters are not required to understand the voting mechanics, they never were, they're not in our national votes and if the system is somewhat fair (which Schulze is) it doesn't make a difference.

What matters (a lot) is how complex casting a vote is. The simpler the ballot is to understand, the better for the voter. That front Schulze beats IRV in simplicity. While with IRV you need to order your prefferences (as in 1st, 2nd, 3rd), Schulze uses a ranking system that allows douplciates - it works perfectly with the good old star-rating which everyone is familiar with.

What happens after the vote is cast could very well be a black box. Of cause that's not ideal, it would nto be open, but as long as the system is fair it would have little to no impact on the voter.

Fortunately neither IRV nor Schulze are black boxes, they are open source and everyone truely wanting to understand themc an (either by reading the source of an implementation or by reading the related paper).

**Comment by binarytemple** [comment]
>>What matters (a lot) is how complex casting a vote is. The simpler the ballot is to understand, the better for the voter. That front Schulze beats IRV in simplicity. While with IRV you need to order your prefferences (as in 1st, 2nd, 3rd), Schulze uses a ranking system that allows douplciates - it works perfectly with the good old star-rating which everyone is familiar with.

I can't understand why a vote wouldn't be 1st Sarah, 2nd Dave, 3rd Peter - why would it need to be 1st Sarah, 2nd Sarah, 3rd Peter? 

>>What happens after the vote is cast could very well be a black box. Of cause that's not ideal, it would nto be open, but as long as the system is fair it would have little to no impact on the voter.

A system that cannot be understood by the voters is sub-optimal in my opinion. It can lead to a trust deficit.

This project is about maintaining and continuing Riak, in my opinion it would be optimal for us to chose something transparent, simple and with plenty of easily understood implementations so we could just pick one off the shelf - wire it up to a google forms spreadsheet and get a result.

I don't like the idea of a black box.

**Comment by Licenser** [comment]
> I can't understand why a vote wouldn't be 1st Sarah, 2nd Dave, 3rd Peter - why would it need to be 1st Sarah, 2nd Sarah, 3rd Peter?

It wouldn't it'd be
Sarah: *****  (or 5)
Dave: *** (or 3)
Peter: ***** (or 5)
Edda: ** (or 2)
Fritz:  (or 0 by default)

> This project is about maintaining and continuing Riak, in my opinion it would be optimal for us to chose something transparent, simple and with plenty of easily understood implementations so we could just pick one off the shelf - wire it up to a google forms spreadsheet and get a result.

All solutions exist in code, putting them in a spreadsheet might not work as votes are suposed to be anonymous so no single person can have a spreadsheet with who voted for what and when we go away from that we can very well just use a fully codified system.

here is the off the shelf erlang implementation for Schulze: https://github.com/kbaird/consensus
~there isn't~ I havn't found one for IRV, I suspect because it's not frequently used in software projects.

> I don't like the idea of a black box.

Neither do I, and neither is a black box, my pain is that for a majority of voters it **can** be a black box as they don't really care. For example, when you cast your last vote did you know what voting method (mathematically) was used? I don't.

**Comment by pjaclark** [comment]
Update from 2017-09-22:

Still planning on the Schulze method, using the implementation provided by Cornell University (used by Ubuntu) here: http://civs.cs.cornell.edu/

Read up, and comment.

**Comment by binarytemple** [comment]
I better appreciate the advantages of Schultz now Vs IRV voting. Withdraw my concern regarding complexity of implementation.
