### ISSUE TITLE
Can we kill the Custom Erlang version?

### ISSUE THREAD

**Issue by pjaclark** [TI-Tokyo/riak-community-admin#16]
Is a custom version of Erlang still needed, or can it be retired and the stock version used? This probably goes hand-in-hand with upgrading to Erlang 19.

**Comment by jadeallenx** [comment]
One of the reasons why Basho used a custom Erlang version was because at the time, many of the efficiency and scale improvements by the WhatsApp team had not been incorporated into the mainline OTP releases.

I believe that situation has resolved itself.  But there still may be a good reason for certain groups to package an OTP release with Riak simply for testing, support and maintenance purposes. (I.e., we are not going to support and test Riak on every possible OTP release out there, just this specific one.)

**Comment by pjaclark** [comment]
Decisions from 2017-09-29:

- Figure out how to kill, and kill.
